import { type SubjectCategory, type Subject, type Verb } from "./types";

type VerbsCollection = Record<SubjectCategory, Verb[]>;

interface Subjects {
  mp: Subject[];
  nmp: Subject[];
}

export const subjects: Subjects = {
  mp: [
    {
      gender: "mp",
      categories: ["persons"],
      nomSg: "student",
      nomPl: "studenci",
      genPl: "studentów",
    },
    {
      gender: "mp",
      categories: ["persons"],
      nomSg: "sąsiad",
      nomPl: "sąsiedzi",
      genPl: "sąsiadów",
    },
    {
      gender: "mp",
      categories: ["persons"],
      nomSg: "artysta",
      nomPl: "artyści",
      genPl: "artystów",
    },
    {
      gender: "mp",
      categories: ["persons"],
      nomSg: "kolega",
      nomPl: "koledzy",
      genPl: "kolegów",
    },
    {
      gender: "mp",
      categories: ["persons"],
      nomSg: "aktor",
      nomPl: "aktorzy",
      genPl: "aktorów",
    },
    {
      gender: "mp",
      categories: ["persons"],
      nomSg: "uczeń",
      nomPl: "uczniowie",
      genPl: "uczniów",
    },
    {
      gender: "mp",
      categories: ["persons"],
      nomSg: "szef",
      nomPl: "szefowie",
      genPl: "szefów",
    },
    {
      gender: "mp",
      categories: ["persons"],
      nomSg: "policjant",
      nomPl: "policjanci",
      genPl: "policjantów",
    },
    {
      gender: "mp",
      categories: ["persons"],
      nomSg: "nauczyciel",
      nomPl: "nauczyciele",
      genPl: "nauczycieli",
    },
  ],
  nmp: [
    {
      gender: "f",
      categories: ["persons"],
      nomSg: "studentka",
      nomPl: "studentki",
      genPl: "studentek",
    },
    {
      gender: "f",
      categories: ["persons"],
      nomSg: "sąsiadka",
      nomPl: "sąsiadki",
      genPl: "sąsiadek",
    },
    {
      gender: "f",
      categories: ["persons"],
      nomSg: "artystka",
      nomPl: "artystki",
      genPl: "artystek",
    },
    {
      gender: "f",
      categories: ["persons"],
      nomSg: "koleżanka",
      nomPl: "koleżanki",
      genPl: "koleżanek",
    },
    {
      gender: "f",
      categories: ["persons"],
      nomSg: "aktorka",
      nomPl: "aktorki",
      genPl: "aktorek",
    },
    {
      gender: "f",
      categories: ["persons"],
      nomSg: "uczennica",
      nomPl: "uczennicy",
      genPl: "uczennic",
    },
    {
      gender: "f",
      categories: ["persons"],
      nomSg: "szefowa",
      nomPl: "szefowe",
      genPl: "szefowych",
    },
    {
      gender: "f",
      categories: ["persons"],
      nomSg: "policjantka",
      nomPl: "policjantki",
      genPl: "policjantek",
    },
    {
      gender: "f",
      categories: ["persons"],
      nomSg: "nauczycielka",
      nomPl: "nauczycielki",
      genPl: "nauczycielek",
    },

    {
      gender: "m",
      categories: ["electronics"],
      nomSg: "telefon",
      nomPl: "telefony",
      genPl: "telefonów",
    },
    {
      gender: "m",
      categories: ["electronics"],
      nomSg: "telewizor",
      nomPl: "telewizory",
      genPl: "telewizorów",
    },
    {
      gender: "m",
      categories: ["electronics"],
      nomSg: "komputer",
      nomPl: "komputery",
      genPl: "komputerów",
    },
    {
      gender: "m",
      categories: ["electronics"],
      nomSg: "piekarnik",
      nomPl: "piekarniki",
      genPl: "piekarników",
    },

    {
      gender: "f",
      categories: ["electronics"],
      nomSg: "pralka",
      nomPl: "pralki",
      genPl: "pralek",
    },
    {
      gender: "f",
      categories: ["electronics"],
      nomSg: "kuchenka",
      nomPl: "kuchenki",
      genPl: "kuchenek",
    },

    {
      gender: "n",
      categories: ["electronics"],
      nomSg: "radio",
      nomPl: "radia",
      genPl: "radiów",
    },

    {
      gender: "m",
      categories: ["furniture"],
      nomSg: "stół",
      nomPl: "stoły",
      genPl: "stołów",
    },
    {
      gender: "m",
      categories: ["furniture"],
      nomSg: "wieszak",
      nomPl: "wieszaki",
      genPl: "wieszaków",
    },

    {
      gender: "f",
      categories: ["furniture"],
      nomSg: "szafa",
      nomPl: "szafy",
      genPl: "szaf",
    },
    {
      gender: "f",
      categories: ["furniture"],
      nomSg: "komoda",
      nomPl: "komody",
      genPl: "komód",
    },

    {
      gender: "n",
      categories: ["furniture"],
      nomSg: "łóżko",
      nomPl: "łóżka",
      genPl: "łóżek",
    },
    {
      gender: "n",
      categories: ["furniture"],
      nomSg: "biurko",
      nomPl: "biurka",
      genPl: "biurek",
    },
    {
      gender: "n",
      categories: ["furniture"],
      nomSg: "krzesło",
      nomPl: "krzesła",
      genPl: "krzeseł",
    },
    {
      gender: "f",
      categories: ["furniture"],
      nomSg: "kanapa",
      nomPl: "kanapy",
      genPl: "kanap",
    },

    {
      gender: "m",
      categories: ["transport"],
      nomSg: "samochód",
      nomPl: "samochody",
      genPl: "samochodów",
    },
    {
      gender: "m",
      categories: ["transport"],
      nomSg: "pociąg",
      nomPl: "pociągi",
      genPl: "pociągów",
    },
    {
      gender: "m",
      categories: ["transport"],
      nomSg: "rower",
      nomPl: "rowery",
      genPl: "rowerów",
    },

    {
      gender: "f",
      categories: ["transport"],
      nomSg: "taksówka",
      nomPl: "taksówki",
      genPl: "taksówek",
    },
    {
      gender: "f",
      categories: ["transport"],
      nomSg: "ciężarówka",
      nomPl: "ciężarówki",
      genPl: "ciężarówek",
    },

    {
      gender: "n",
      categories: ["transport"],
      nomSg: "pendolino",
      nomPl: "pendolina",
      genPl: "pendolin",
    },

    {
      gender: "m",
      categories: ["small"],
      nomSg: "pad",
      nomPl: "pady",
      genPl: "padów",
    },
    {
      gender: "m",
      categories: ["small"],
      nomSg: "pilot",
      nomPl: "piloty",
      genPl: "pilotów",
    },
    {
      gender: "m",
      categories: ["small"],
      nomSg: "krem",
      nomPl: "kremy",
      genPl: "kremów",
    },
    {
      gender: "m",
      categories: ["small"],
      nomSg: "długopis",
      nomPl: "długopisy",
      genPl: "długopisów",
    },

    {
      gender: "f",
      categories: ["small"],
      nomSg: "butelka",
      nomPl: "butelki",
      genPl: "butelek",
    },
    {
      gender: "f",
      categories: ["small"],
      nomSg: "nakrętka",
      nomPl: "nakrętki",
      genPl: "nakrętek",
    },
    {
      gender: "f",
      categories: ["small"],
      nomSg: "książka",
      nomPl: "książki",
      genPl: "książek",
    },
    {
      gender: "f",
      categories: ["small"],
      nomSg: "świeczka",
      nomPl: "świeczki",
      genPl: "świeczek",
    },
    {
      gender: "f",
      categories: ["small"],
      nomSg: "puszka",
      nomPl: "puszki",
      genPl: "puszek",
    },

    {
      gender: "n",
      categories: ["small"],
      nomSg: "jabłko",
      nomPl: "jabłka",
      genPl: "jabłek",
    },
    {
      gender: "n",
      categories: ["small"],
      nomSg: "pudełko",
      nomPl: "pudełka",
      genPl: "pudełek",
    },
    {
      gender: "n",
      categories: ["small"],
      nomSg: "ciasto",
      nomPl: "ciasta",
      genPl: "ciast",
    },
  ],
};

export const verbs: VerbsCollection = {
  persons: [
    {
      base: "czytać",
      n: "czytało",
      m: "czytał",
      f: "czytała",
      nmp: "czytały",
      mp: "czytali",
      after: "książkę",
    },
    {
      base: "jechać",
      n: "jechało",
      m: "jechał",
      f: "jechała",
      nmp: "jechały",
      mp: "jechali",
      after: "pociągiem",
    },
    {
      base: "siedzieć",
      n: "siedziało",
      m: "siedział",
      f: "siedziała",
      nmp: "siedziały",
      mp: "siedzieli",
      after: "na krzesłach",
    },
    {
      base: "pisać",
      n: "pisało",
      m: "pisał",
      f: "pisała",
      nmp: "pisały",
      mp: "pisali",
      after: "list",
    },
    {
      base: "bawić się",
      n: "bawiło się",
      m: "bawił się",
      f: "bawiła się",
      nmp: "bawiły się",
      mp: "bawili się",
      after: "z kotem i psem",
    },
    {
      base: "odkurzać",
      n: "odkurzało",
      m: "odkurzał",
      f: "odkurzała",
      nmp: "odkurzały",
      mp: "odkurzali",
      after: "pokój",
    },
    {
      base: "oglądać",
      n: "oglądało",
      m: "oglądał",
      f: "oglądała",
      nmp: "oglądały",
      mp: "oglądali",
      after: "film",
    },
    {
      base: "słuchać",
      n: "słuchało",
      m: "słuchał",
      f: "słuchała",
      nmp: "słuchały",
      mp: "słuchali",
      after: "muzyki",
    },
    {
      base: "być",
      n: "było",
      m: "był",
      f: "była",
      nmp: "były",
      mp: "byli",
      after: "pod drzwiami",
    },
  ],
  electronics: [
    {
      base: "zużywać",
      n: "zużywało",
      m: "zużywał",
      f: "zużywała",
      nmp: "zużywały",
      after: "dużo prądu",
    },
    {
      base: "włączać się",
      n: "włączało się",
      m: "włączał się",
      f: "włączała się",
      nmp: "włączały się",
      before: "zbyt długo",
    },
    {
      base: "wyłączyć się",
      n: "włączyło się",
      m: "włączył się",
      f: "włączyła się",
      nmp: "włączyły się",
      before: "nagle",
    },
    {
      base: "spalić się",
      n: "spaliło się",
      m: "spalił się",
      f: "spaliła się",
      nmp: "spaliły się",
    },
    {
      base: "zepsuć się",
      n: "zepsuło się",
      m: "zepsuł się",
      f: "zepsuła się",
      nmp: "zepsuły się",
    },
    {
      base: "kosztować",
      n: "kosztowało",
      m: "kosztował",
      f: "kosztowała",
      nmp: "kosztowały",
      before: "dużo",
    },
  ],
  furniture: [
    {
      base: "stać",
      n: "stało",
      m: "stał",
      f: "stała",
      nmp: "stały",
      after: "na środku pokoju",
    },
    {
      base: "służyć",
      n: "służyło",
      m: "służył",
      f: "służyła",
      nmp: "służyły",
      after: "do przechowywania ubrań",
    },
    {
      base: "wyglądać",
      n: "wyglądało",
      m: "wyglądał",
      f: "wyglądała",
      nmp: "wyglądały",
      before: "brzydko",
    },
    {
      base: "skrzypieć",
      n: "skrzypiało",
      m: "skrzypiał",
      f: "skrzypiała",
      nmp: "skrzypiało",
      before: "głośnie",
    },
    {
      base: "zabierać",
      n: "zabierało",
      m: "zabierał",
      f: "zabierała",
      nmp: "zabierały",
      after: "dużo miejsca",
    },
    {
      base: "pasować",
      n: "pasowało",
      m: "pasował",
      f: "pasowała",
      nmp: "pasowały",
      after: "do innych mebli",
    },
  ],
  transport: [
    {
      base: "zahamować",
      n: "zahamowało",
      m: "zahamował",
      f: "zahamowała",
      nmp: "zahamowały",
      before: "gwałtownie",
    },
    {
      base: "zbliżać się",
      n: "zbliżało się",
      m: "zbliżał się",
      f: "zbliżała się",
      nmp: "zbliżały się",
      after: "do miasta",
    },
    {
      base: "zwalniać",
      n: "zwalniało",
      m: "zwalniał",
      f: "zwalniała",
      nmp: "zwalniały",
    },
    {
      base: "zatrzymać się",
      n: "zatrzymało się",
      m: "zatrzymał się",
      f: "zatrzymała się",
      nmp: "zatrzymały się",
    },
  ],
  small: [
    {
      base: "leżeć",
      n: "leżało",
      m: "leżał",
      f: "leżała",
      nmp: "leżały",
      after: "na biurku",
    },
    {
      base: "zniknąć",
      n: "zniknęło",
      m: "zniknął",
      f: "zniknęła",
      nmp: "zniknęły",
    },
    {
      base: "kosztować",
      n: "kosztowało",
      m: "kosztował",
      f: "kosztowała",
      nmp: "kosztowały",
      after: "300 złotych",
    },
    {
      base: "trafić",
      n: "trafiło",
      m: "trafił",
      f: "trafiła",
      nmp: "trafiły",
      after: "w głowę",
    },
    {
      base: "spaść",
      n: "spadło",
      m: "spadł",
      f: "spadła",
      nmp: "spadły",
      after: "na podłogę",
    },
  ],
};
